version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.jetbrains.kotlin*"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
    groups:
      major:
        patterns:
          - "*"
        update-types:
          - "major"
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      major:
        patterns:
          - "*"
        update-types:
          - "major"
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "eclipse-temurin"
        versions: [">= 22"]
    groups:
      major:
        patterns:
          - "*"
        update-types:
          - "major"
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      major:
        patterns:
          - "*"
        update-types:
          - "major"
      minor:
        patterns:
          - "*"
        update-types:
          - "minor"
      patch:
        patterns:
          - "*"
        update-types:
          - "patch"
