FROM liquibase/liquibase:5.0

# Kopiere den kompletten Ordner 'db', damit die relativen Pfade wie 'db/changelog/changes/...' in den Master-YAMLs stimmen
COPY backend/src/main/resources/db /liquibase/db

CMD ["update"]
