ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ org.javafreedom.kdiab.profiles.ApplicationKt.module ]
    }
}

jwt {
    domain = "org.javafreedom.kdiab"
    domain = ${?JWT_DOMAIN}
    audience = "profile"
    audience = ${?JWT_AUDIENCE}
    realm = "kdiab-profiles"
    realm = ${?JWT_REALM}
    secret = "secret"
    secret = ${?JWT_SECRET}
}

storage {
    driverClassName = "org.postgresql.Driver"
    jdbcUrl = "jdbc:postgresql://localhost:5432/kdiab-profiles"
    jdbcUrl = ${?JDBC_URL}
    username = "postgres"
    username = ${?DB_USER}
    password = "password"
    password = ${?DB_PASSWORD}
    maximumPoolSize = 3
    maximumPoolSize = ${?DB_POOL_SIZE}
    isAutoCommit = false
    transactionIsolation = "TRANSACTION_REPEATABLE_READ"
}
